expose the current running exception to user code
ElementaryFramework/WaterPipe pull request #5
Opened 2020-07-17 13:44 UTC by manitra

In case of exception during pipe exception, it will be stored and make available to user code using the `getRunningException` function.
It is intended to be used in middlewares (in beforeSend hook) or in the error handlers.

This change has been done in the least intrusive way possible : 
- it is completely backward compatible 
- there are no change in middlewares nor error handlers signatures

2020-07-30 15:56 UTC, na2axl requested changes
Hello @manitra, thanks for pushing these changes. I'm totally OK to merge it, please just fix the requested changes before :-)

2020-07-30 15:56 UTC, na2axl commented on src/WaterPipe/WaterPipe.php
> +     * In case an exception occures during pipe execution, it will be
```suggestion
     * In case an exception occurs during pipe execution, it will be
```

Little typo here :-)

2020-07-30 15:56 UTC, na2axl commented on src/WaterPipe/WaterPipe.php
> +     * stored here for user code to read in middlewares and errorhandlers
```suggestion
     * stored here for user code to read in middlewares and error handlers
```

A forgotten space

2020-07-30 15:56 UTC, na2axl commented on src/WaterPipe/WaterPipe.php
> +     */
```suggestion
     * @return \Exception
     */
```

Useful for intellisense

2020-07-30 15:56 UTC, na2axl commented on src/WaterPipe/WaterPipe.php
> +     * @var Exception
```suggestion
     * @var \Exception
```

Intellisense can break here for some IDE without the backslash for native, not imported (there is no `use Exception` in the file), PHP classes

2020-07-31 07:07 UTC, manitra commented
Done :)

2020-07-31 10:10 UTC, na2axl approved these changes
LGTM !

2020-07-31 10:11 UTC, merged